import type {LucideIcon} from 'lucide-react';
import {ArrowRight, Heart, MessageCircle} from 'lucide-react';
import {ToyIcon} from '@/components/toy-icon';
import {Header,Footer} from '../page';

type Feature={icon:LucideIcon,title:string,text:string};
type Spotlight={number:string,kicker:string,title:string,tags:string[],text:string};
type Props={theme:'theme-blue'|'theme-green'|'theme-gold',eyebrow:string,title:string,englishName:string,intro:string,age:string,duration:string,frequency:string,toy:'lion'|'train'|'bear'|'rainbow',visualNote:string,sectionTitle:string,sectionText:string,spotlights:Spotlight[],focusTitle:string,features:Feature[]};

export function CoursePage({theme,eyebrow,title,englishName,intro,age,duration,frequency,toy,visualNote,sectionTitle,sectionText,spotlights,focusTitle,features}:Props){return <><Header/><main className={'playgroup-page program-page '+theme}><section className="course-detail-hero wrap"><div className="course-detail-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}<br/><span>{englishName}</span></h1><p>{intro}</p><div className="course-detail-stats"><span><b>{age}</b>適合年齡</span><span><b>{duration}</b>課程安排</span><span><b>{frequency}</b>上課模式</span></div><div className="row"><a className="button" href="/timetable">查看時間表 <ArrowRight size={18}/></a><a className="button outline light" href="/branches">尋找分會</a></div></div><div className="course-detail-visual program-visual"><span className="visual-orbit"/><ToyIcon kind={toy} className="playgroup-lion program-toy"/><span className="visual-note"><Heart size={17}/> {visualNote}</span></div></section><section className="wrap course-detail-section"><div className="course-detail-lead"><span className="eyebrow">A GENTLE NEXT STEP</span><h2>{sectionTitle}</h2><p>{sectionText}</p></div><div className="pathway-grid">{spotlights.map(item=><article className="pathway-card program-pathway" key={item.number}><span className="stage-number">{item.number}</span><p className="stage-age">{item.kicker}</p><h3>{item.title}</h3><div className="stage-groups">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div><p>{item.text}</p></article>)}</div></section><section className="wrap course-detail-section"><div className="course-detail-lead"><span className="eyebrow">WHAT CHILDREN PRACTISE</span><h2>{focusTitle}</h2></div><div className="focus-grid">{features.map(({icon:Icon,title:featureTitle,text})=><article className="focus-card" key={featureTitle}><Icon aria-hidden="true"/><h3>{featureTitle}</h3><p>{text}</p></article>)}</div></section><section className="wrap course-detail-cta program-cta"><ToyIcon kind={toy} className="cta-rainbow"/><div><span className="eyebrow">FIND A CLASS NEAR YOU</span><h2>準備好展開下一步？</h2><p>各分會的開班時間、名額及收費可能不同，歡迎向就近分會查詢最新安排。</p></div><div className="row"><a className="button" href="/branches"><MessageCircle size={18}/> 聯絡分會</a><a className="text-link" href="/timetable">查看課程時間表 <ArrowRight size={16}/></a></div></section></main><Footer/></>}
