import {Activity, ArrowRight, Ear, Hand, Heart, MessageCircle, Shapes, Users} from 'lucide-react';
import {ToyIcon} from '@/components/toy-icon';
import {Header,Footer} from '../../page';

const focuses=[
  {icon:Activity,title:'大小肌肉發展',text:'以合適的動作遊戲，為站立、步行、執筆與日後學習打好基礎。'},
  {icon:Hand,title:'手眼與腳眼協調',text:'透過拿取、觸碰與身體活動，逐步提升動作控制及協調能力。'},
  {icon:Shapes,title:'感覺統合與認知',text:'運用顏色、形狀、聲音與質感，支持認知、專注力及語言發展。'},
  {icon:Ear,title:'聆聽與理解指令',text:'在有趣的遊戲流程中建立聆聽習慣，學習理解及回應簡單指令。'},
  {icon:Users,title:'社交與自信',text:'在安全的親子環境中與人互動，練習輪候、分享及正面社交行為。'},
  {icon:MessageCircle,title:'語言與表達',text:'從歌曲、故事與互動遊戲中累積詞彙，鼓勵孩子表達需要與想法。'},
];

export default function PlaygroupPage(){return <><Header/><main className="playgroup-page"><section className="course-detail-hero wrap"><div className="course-detail-copy"><span className="eyebrow">LITTLE SENSES, BIG DISCOVERIES</span><h1>嬰幼兒潛能發展<br/><span>Playgroup</span></h1><p>以心理發展為本，透過感官、音樂、故事與親子遊戲，陪伴寶寶在每個成長階段建立安全感、自信與探索能力。</p><div className="course-detail-stats"><span><b>6個月至2歲</b>適合年齡</span><span><b>10堂</b>每期課程</span><span><b>1小時</b>每星期一堂</span></div><div className="row"><a className="button" href="/timetable">查看時間表 <ArrowRight size={18}/></a><a className="button outline light" href="/branches">尋找分會</a></div></div><div className="course-detail-visual"><span className="visual-orbit"/><ToyIcon kind="lion" className="playgroup-lion"/><span className="visual-note"><Heart size={17}/> 親子一起探索</span></div></section><section className="wrap course-detail-section"><div className="course-detail-lead"><span className="eyebrow">GROWING TOGETHER</span><h2>每個月齡，都有自己的發現</h2><p>課程按寶寶的成長需要分組，讓活動難度、互動方式和學習目標更貼合當下的發展階段。</p></div><div className="pathway-grid"><article className="pathway-card baby-stage"><span className="stage-number">01</span><p className="stage-age">6–12 個月</p><h3>建立安全感，從感官認識世界</h3><div className="stage-groups"><span>6–9 個月</span><span>9–12 個月</span></div><p>在照顧者陪伴下，寶寶透過感知動作探索環境，逐步建立信任與安全感，同時促進腦部、肌肉及身體協調發展。</p></article><article className="pathway-card toddler-stage"><span className="stage-number">02</span><p className="stage-age">12–24 個月</p><h3>鼓勵主動探索，發展自主能力</h3><div className="stage-groups"><span>12–15 個月</span><span>15–18 個月</span><span>18–24 個月</span></div><p>幼兒開始主動探索外界，課程透過遊戲支持認知、語言、專注力、身體協調與社交能力，為日後學習做好準備。</p></article></div></section><section className="wrap course-detail-section"><div className="course-detail-lead"><span className="eyebrow">LEARNING THROUGH PLAY</span><h2>玩樂背後，藏著六種成長練習</h2></div><div className="focus-grid">{focuses.map(({icon:Icon,title,text})=><article className="focus-card" key={title}><Icon aria-hidden="true"/><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="wrap course-detail-cta"><ToyIcon kind="rainbow" className="cta-rainbow"/><div><span className="eyebrow">READY TO PLAY?</span><h2>為寶寶找到合適的 Playgroup</h2><p>各分會的開班時間、名額及收費可能不同，歡迎向就近分會查詢最新安排。</p></div><div className="row"><a className="button" href="/branches"><MessageCircle size={18}/> 聯絡分會</a><a className="text-link" href="/timetable">查看課程時間表 <ArrowRight size={16}/></a></div></section></main><Footer/></>}
